[arch]
name=Arch Linux (rolling)
image=quay.io/toolbx/arch-toolbox:latest
icon=distributor-logo-archlinux

[debian13]
name=Debian 13 (Trixie)
image=quay.io/toolbx-images/debian-toolbox:13
icon=distributor-logo-debian

[debian12]
name=Debian 12 (Bookworm)
image=quay.io/toolbx-images/debian-toolbox:12
icon=distributor-logo-debian

[debian_sid]
name=Debian Unstable (Sid)
image=quay.io/toolbx-images/debian-toolbox:unstable
icon=distributor-logo-debian

[kali]
name=Kali Linux (rolling)
image=docker.io/kalilinux/kali-rolling:latest
icon=distributor-logo-kalilinux

[mint21]
name=Linux Mint 21.1
image=docker.io/linuxmintd/mint21.1-amd64
icon=distributor-logo-linuxmint

[deepin23]
name=Deepin 23 (Beige)
image=docker.io/linuxdeepin/deepin:beige
icon=distributor-logo-deepin

[deepin20]
name=Deepin 20 (Apricot)
image=docker.io/linuxdeepin/apricot
icon=distributor-logo-deepin

[ubuntu24.04]
name=Ubuntu 24.04 LTS (Noble)
image=quay.io/toolbx/ubuntu-toolbox:24.04
icon=distributor-logo-ubuntu

[ubuntu22.04]
name=Ubuntu 22.04 LTS (Jammy)
image=quay.io/toolbx/ubuntu-toolbox:22.04
icon=distributor-logo-ubuntu

[ubuntu20.04]
name=Ubuntu 20.04 LTS (Focal)
image=quay.io/toolbx/ubuntu-toolbox:20.04
icon=distributor-logo-ubuntu

[fedora43]
name=Fedora 43
image=quay.io/fedora/fedora-toolbox:43
icon=distributor-logo-fedora

[centos10]
name=CentOS Stream 10
image=quay.io/toolbx-images/centos-toolbox:stream10
icon=distributor-logo-centos

[centos9]
name=CentOS Stream 9
image=quay.io/toolbx-images/centos-toolbox:stream9
icon=distributor-logo-centos

[centos8]
name=CentOS Stream 8
image=quay.io/toolbx-images/centos-toolbox:stream8
icon=distributor-logo-centos

[rhel10]
name=Red Hat Enterprise Linux 10 (UBI)
image=registry.access.redhat.com/ubi10/toolbox
icon=distributor-logo-rhel

[alma10]
name=AlmaLinux 10
image=quay.io/toolbx-images/almalinux-toolbox:10
icon=distributor-logo-almalinux

[rocky10]
name=Rocky Linux 10
image=quay.io/toolbx-images/rockylinux-toolbox:10
icon=distributor-logo-rockylinux

[opensuse_tw]
name=openSUSE Tumbleweed
image=registry.opensuse.org/opensuse/distrobox:latest
icon=distributor-logo-opensuse

[opensuse_leap]
name=openSUSE Leap
image=registry.opensuse.org/opensuse/leap:latest
icon=distributor-logo-opensuse

[alpine_edge]
name=Alpine Linux Edge
image=quay.io/toolbx-images/alpine-toolbox:edge
icon=distributor-logo-alpine

[alpine_latest]
name=Alpine Linux Latest
image=quay.io/toolbx-images/alpine-toolbox:latest
icon=distributor-logo-alpine

[void_glibc]
name=Void Linux (Glibc)
image=ghcr.io/void-linux/void-glibc-full:latest
icon=distributor-logo-void

[void_musl]
name=Void Linux (Musl)
image=ghcr.io/void-linux/void-musl-full:latest
icon=distributor-logo-void

[gentoo]
name=Gentoo Linux
image=docker.io/gentoo/stage3:latest
icon=distributor-logo-gentoo

[slackware]
name=Slackware Current
image=docker.io/vbatts/slackware:current
icon=distributor-logo-slackware

[vanilla]
name=Vanilla OS (VSO)
image=ghcr.io/vanilla-os/vso:main
icon=distributor-logo-vanilla
